### ISSUE TITLE
How about https://platform.dlite.io?

### ISSUE THREAD

**Issue by renaudpawlak** [fiatjaf/awesome-loginless#29]
I would suggest to add this service (low-code IDE for web front ends), which does not require any registration to start working and create projets. It uses a local-first approach.

Probably in the 'Development' section.

* [dLite.io](https://platform.dlite.io/) - Low-code platform for building Web front ends with a local-first approach. Thanks to the local-first approch, you save your projects locally (no registration required). You may use an optional authentication plugin to benefit project and data syncing/sharing (more info [here](https://www.dlite.io)).

**Comment by fiatjaf** [comment]
I think this doesn't fit, since it's just a client-side app, not a service. Or rather the service part does require a login.
